[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "."
    exclude = [
      "./impressum.html",
      "./datenschutz.html"
    ]

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    sitemapPath = "/sitemap.xml"